<?php


use Phinx\Migration\AbstractMigration;

class AlterTableUserMoneyAdd extends AbstractMigration
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-abstractmigration-class
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function up()
    {

        $table = $this->table('user_money_add');
        $table->changeColumn('uma_note', ColumnTypes::TEXT, [
            ColumnOptions::LIMIT => 4294967295
        ]);
        $table->update();
    }

    public function down()
    {
        parent::down(); // TODO: Change the autogenerated stub
    }
}
