<?php


use Phinx\Migration\AbstractMigration;

class AlterUserTable extends AbstractMigration
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-abstractmigration-class
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function up()
    {

        $table = $this->table('users');
        $table->changeColumn('use_id_vatgia', ColumnTypes::INTEGER, [
            ColumnOptions::DEFAULT => 0
        ]);
        $table->changeColumn('use_active', ColumnTypes::INTEGER, [
            ColumnOptions::LIMIT => 1,
            ColumnOptions::DEFAULT => 0
        ]);
        $table->changeColumn('use_money_add', ColumnTypes::FLOAT, [
            ColumnOptions::DEFAULT => 0
        ]);
        $table->changeColumn('use_commission', ColumnTypes::FLOAT, [
            ColumnOptions::DEFAULT => 0
        ]);

    }

    public function down()
    {
        parent::down(); // TODO: Change the autogenerated stub
    }
}
